# This is the configuration file for Koyeb.
# It tells Koyeb exactly how to build and run your bot.

# Give your app a name
name: drednot-game-client

# Define the services to run. We only have one.
services:
  - name: game-client-worker
    # Use the "Free" instance type
    instance_type: free
    # Configure the health check to be a simple TCP check
    health_checks:
      - type: tcp
    # Define the build and run commands
    build:
      command: npm install && npx puppeteer browsers install chrome
      # The start command
    run:
      command: npm start
    # Set the scaling to always have 1 instance running
    scaling:
      min: 1
      max: 1
    # Tell Koyeb to get the code from your GitHub repo
    git:
      branch: main
      repository: Justlipcoolman/drednot-game-client # MAKE SURE THIS IS YOUR REPO NAME
    # Define your environment variables
    env:
      - key: BOT_SERVER_URL
        # IMPORTANT: This must be a secret. We will set its value in the dashboard.
        from: secret
        value: BOT_SERVER_URL_SECRET
